spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zakazime
    username: postgres
    password: postgres
  flyway:
    baseline-description: Initial setup
    user: postgres
    password: postgres
    validateMigrationNaming: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    com:
      dglisic:
        zakazime:
          business: DEBUG
