spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zakazivanje
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml

logging:
  level:
    liquibase: info
