spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zakazime
    username: postgres
    password: postgres
  flyway:
    baseline-description: Initial setup
    user: postgres
    password: postgres
    validateMigrationNaming: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: dglisic.zakazime@gmail.com
    password: "zyyq qmev limq rutl"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    com:
      dglisic:
        zakazime:
          business: DEBUG
