spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zakazime
    username: postgres
    password: postgres
  flyway:
    baseline-description: Initial setup
    user: postgres
    password: postgres
    validateMigrationNaming: true

logging:
  level:
    org.springframework.security: DEBUG
