spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zakazime
    username: postgres
    password: postgres
  flyway:
    baseline-description: Initial setup
    user: postgres
    password: postgres
    validateMigrationNaming: true

springdoc:
  api-docs:
    path: /api-docs

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
