version: '3'

services:
  postgres-zakazime:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zakazime
    volumes:
      - ~/postgres/zakazime/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin-zakazime:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    depends_on:
      - postgres-zakazime
